import { Heebo, Roboto } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Providers } from "@/redux/Providers";
import { LayoutProvider } from '@/context/useLayoutContext';
import { ToastContainer } from "react-toastify";

const heebo = Heebo({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-heebo",
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${heebo.variable} ${roboto.variable}`}>
        <LayoutProvider>
          <Providers>
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
          </Providers>
        </LayoutProvider>
      </body>
    </html>
  );
}
